language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install
  - cp config.sample.php config.php

script: phpunit --configuration phpunit.xml.dist
